### PR TITLE
add link to paramidib

### PR DESCRIPTION
**Pull request by pietroppeter**
https://pietroppeter.github.io/paramidib/

see also: https://pietroppeter.github.io/adventofnim/2021/day03.html#whale_music

being published on nimble packages, once https://github.com/nim-lang/packages/pull/2080 is merged it will be installable with `nimble install paramidib`

from a fan :)

### CODE REVIEW

**Comment by oakes** [comment]
That is so cool, thanks for making this.

BTW in case you haven't tried it yet, you can actually send the audio to an `audio` tag without having to save a file to the disk, by generating a [data URI](https://en.wikipedia.org/wiki/Data_URI_scheme) instead. Here's an example...

```nim
let wav = sound.writeMemory(res.data, res.data.len.uint32, sampleRate)
let dataUri = "data:audio/wav;base64," & base64.encode(wav)
# put daraUri in the audio control's src
```

I tried this before and it worked in chrome and firefox :D

**Comment by pietroppeter** [comment]
> That is so cool, thanks for making this.

Thank you, I had great fun, paramidi is very cool! It was quite some time I wanted to play with it and I finally had the chance, before doing this I was not even aware of the "recent" json api for scores, which was very useful for my advent of code adventures!

> BTW in case you haven't tried it yet, you can actually send the audio to an audio tag without having to save a file to the disk

that looks very nice, no I did not know about it (it could be used to have a single `saveAudio` command in Nimib).

Just to be clear the size of the encoded wav is not optimized through this in some way, right (if anything base64 encoding should make it worse)? Because I realized doing the advent of code thing, that a 10 minutes wav goes above 100MB, which is an issue when committing to GitHub (I should avoid doing that and regenerate on the fly when serving the documentation, but it is very convenient so I am being lazy). If that is the case I think it could be useful for shorter audio elements, but otherwise I guess it might slow down the parsing of the html page.

**Comment by oakes** [comment]
Yep base64 will make it 33% larger. If you encode it as mp3 you could cut the size down by a lot. Or if you want to play hard mode, you could compile it with web assembly and generate the audio completely in the browser, in which case there would be no need to commit the generated data to git. I have a working example of this, i'll put it somewhere public when i get the chance.

**Comment by pietroppeter** [comment]
> If you encode it as mp3 you could cut the size down by a lot

I see that the starter example uses parasound to write the wave file and there is no support for writing mp3 file, correct? Do you other ways to write mp3 files? It would be nice to support them.

**Comment by oakes** [comment]
No it doesn't support mp3 encoding for now.

**Pull request merged**
