### PR TITLE
Add ability to set volume

### PR DESCRIPTION
**Pull request by neroist**

### CODE REVIEW

**Comment by oakes** [comment]
Thanks for the PR. One thing you are missing is a default volume. In `initContext` you need to add something like `volume: 100` or else it will default to 0 and thus not play any sound when it isn't explicitly set.

**Comment by neroist** [comment]
Thanks, added!

**Comment by oakes** [comment]
Great, thanks

**Comment by neroist** [comment]
I was also thinking to add something like this to the readme:

```nim
# you can also set volume, which is helpful for dynamics
(piano, (volume: 120), c, d, e, f)
```

**Comment by oakes** [comment]
Sure go ahead. BTW it also needs to be added to the JsonNode API. Basically right after [this branch](https://github.com/paranim/paramidi/blob/7bc20040c68417b1cb7a9e37ef9c04e6241b0b49/src/paramidi.nim#L705) it just needs a branch for volume that looks exactly the same.

**Pull request merged**
